version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /etc/nginx/certs
      - /usr/share/nginx/html
      - /srv/config/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    environment:
      TZ: 'Asia/Seoul'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "nginx-proxy"

  gitlab-ce:
    image: gitlab/gitlab-ce
    restart: always
    container_name: gitlab-ce
    environment:
      TZ: 'Asia/Seoul'
      VIRTUAL_HOST: gitlab.example.com
      LETSENCRYPT_HOST: gitlab.example.com
      LETSENCRYPT_EMAIL: starrybleu@gmail.com
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "example@gmail.com"
        gitlab_rails['smtp_password'] = "1234"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        nginx['client_max_body_size'] = 0
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        registry['enable'] = true
        registry_external_url 'https://gitlab.example.com:4567'
        registry_nginx['listen_port'] = 4567
        registry_nginx['listen_https'] = true
        registry_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
    hostname: 'gitlab.example.com'
    ports:
      - "8022:22"
      - "4567:4567"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/config:/etc/gitlab
      - /srv/logs/gitlab-ce:/var/log/gitlab
      - /srv/data/gitlab-ce:/var/opt/gitlab
      - /etc/nginx/certs:/etc/gitlab/ssl:ro

  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/mongo/data:/data/db

networks:
  default:
    external:
      name: nginx-net